feat: add charmed_zookeeper plugin
marcoppenheimer/sos pull request #2
Opened 2024-03-04 15:29 UTC by marcoppenheimer

Code is mostly self-explanatory.

To test oneself on an LXD cloud:

```bash
juju add-model temp
juju deploy zookeeper --channel edge -n 3
juju deploy kafka --channel edge -n 3
juju relate kafka zookeeper
juju deploy kafka-test-app --series=jammy --channel=edge --config role=producer --config topic_name="HOT-TOPIC" --config num_messages=100000 --force producer
juju deploy kafka-test-app --series=jammy --channel=edge --config role=consumer --config topic_name="HOT-TOPIC" --config num_messages=100000 --force consumer
juju relate kafka producer
juju relate kafka consumer

# wait for active/idle

juju ssh zookeeper/0 sudo -i

# in SSH session

git clone https://github.com/marcoppenheimer/sos.git
cd sos
git checkout feat/charmed_zookeeper
python3 setup.py install
./bin/sos report --only-plugins "charmed_zookeeper"
cd /tmp
tar xvf *.xz

# inspect the actual outputted files as you wish

ls -lah ./**/var/snap/charmed-zookeeper/current/etc/zookeeper
ls -lah ./**/var/snap/charmed-zookeeper/common/var/log/zookeeper
ls -lah ./**/sos_commands/charmed_zookeeper
```

2024-03-05 11:38 UTC, zmraul requested changes

2024-03-05 11:38 UTC, zmraul commented on sos/report/plugins/charmed_zookeeper.py
> +                f"{PATHS['CONF']}/*.pem",
I think `/*.key` as well?

2024-03-05 12:04 UTC, marcoppenheimer commented on sos/report/plugins/charmed_zookeeper.py
> +                f"{PATHS['CONF']}/*.pem",
Ah, same for Kafka too. I'll add.

2024-03-11 14:29 UTC, deusebio commented
Ops, this did not showed up on my review list :(

I'm very happy with the changes. Great that keys were excluded. Are they excluded for Kafka as well already?

2024-03-11 14:29 UTC, deusebio commented
LGTM

2024-03-14 12:13 UTC, merged